/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include<sys/wait.h>
#include<utime.h>
#ifndef _DEXOPT
#define _DEXOPT
#ifdef __cplusplus
#define  LOG_TAG    "OpenAtlasDexOpt"
#define  LOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)
#define  LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)
#define  LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)

extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_openatlas_dexopt_InitExecutor_dexopt
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
